name: Health check poja

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4.1.6

      - uses: actions/setup-java@v4.2.1
        with:
          java-version: '21'
          distribution: 'corretto'

      - run: chmod +x gradlew

      - uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Create and activate virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install pip and dependencies
        run: |
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install awscli

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.POJA_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.POJA_AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-3

      - name: Connect to Private CodeArtifact
        run: |
          aws codeartifact login --tool pip --repository harena-mav --domain patrimoine-harena --domain-owner 016161980486 --region eu-west-3

      - name: Install poja
        run: |
          source venv/bin/activate
          pip install poja --upgrade

      - name: Run POJA tool
        run: |
          source venv/bin/activate
          python -m poja --poja-conf poja.yml --output-dir=. --github-username=${{ secrets.POJA_GH_USERNAME }} --github-token=${{ secrets.POJA_GH_TOKEN }}

      - name: Check for changes
        run: |
          git diff --exit-code
